In [1]:
import torch

## Scalar

In [2]:
scalar1 = torch.tensor([1.])
print(scalar1)

tensor([1.])


In [3]:
scalar2 = torch.tensor([3.])
print(scalar2)

tensor([3.])


In [5]:
add_scalar = scalar1 + scalar2
print(add_scalar)

tensor([4.])


In [6]:
sub_scalar = scalar1 - scalar2
print(sub_scalar)

tensor([-2.])


In [7]:
mul_scalar = scalar1 * scalar2
print(mul_scalar)

tensor([3.])


In [8]:
div_scalar = scalar1 / scalar2
print(div_scalar)

tensor([0.3333])


In [9]:
torch.add(scalar1,scalar2)

tensor([4.])

In [10]:
torch.sub(scalar1, scalar2)

tensor([-2.])

In [11]:
torch.mul(scalar1, scalar2)

tensor([3.])

In [12]:
torch.div(scalar1, scalar2)

tensor([0.3333])

## Vector

In [13]:
vector1 = torch.tensor([1., 2., 3.])
print(vector1)

tensor([1., 2., 3.])


In [14]:
vector2 = torch.tensor([4., 5., 6.])
print(vector2)

tensor([4., 5., 6.])


In [15]:
add_vector = vector1 + vector2
print(add_vector)

tensor([5., 7., 9.])


In [16]:
sub_vector = vector1 - vector2
print(sub_vector)

tensor([-3., -3., -3.])


In [17]:
mul_vector = vector1 * vector2
print(mul_vector)

tensor([ 4., 10., 18.])


In [18]:
div_vector = vector1 / vector2
print(div_vector)

tensor([0.2500, 0.4000, 0.5000])


In [19]:
torch.add(vector1, vector2)

tensor([5., 7., 9.])

In [20]:
torch.sub(vector1, vector2)

tensor([-3., -3., -3.])

In [21]:
torch.mul(vector1, vector2)

tensor([ 4., 10., 18.])

In [22]:
torch.div(vector1, vector2)

tensor([0.2500, 0.4000, 0.5000])

In [23]:
# 벡터 내적은 dot을 이용해 가능
torch.dot(vector1, vector2)

tensor(32.)

## Matrix

In [24]:
matrix1 = torch.tensor([[1., 2.], [3., 4.]])
print(matrix1)

tensor([[1., 2.],
        [3., 4.]])


In [25]:
matrix2 = torch.tensor([[5., 6.], [7., 8.]])
print(matrix2)

tensor([[5., 6.],
        [7., 8.]])


In [26]:
torch.add(matrix1, matrix2)

tensor([[ 6.,  8.],
        [10., 12.]])

In [27]:
torch.sub(matrix1, matrix2)

tensor([[-4., -4.],
        [-4., -4.]])

In [28]:
torch.mul(matrix1, matrix2)

tensor([[ 5., 12.],
        [21., 32.]])

In [29]:
torch.div(matrix1, matrix2)

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])

In [30]:
torch.matmul(matrix1, matrix2)

tensor([[19., 22.],
        [43., 50.]])

## tensor

In [32]:
tensor1 = torch.tensor([[[1., 2.], [3., 4.]], [[5., 6.], [7., 8.]]])
print(tensor1)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [34]:
tensor2 = torch.tensor([[[9., 10.], [11., 12.]], [[13., 14.], [15., 16.]]])
print(tensor2)

tensor([[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]])


In [36]:
sum_tensor = tensor1 + tensor2
print(sum_tensor)

tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])


In [37]:
sub_tensor = tensor1 - tensor2
print(sub_tensor)

tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])


In [38]:
mul_tensor = tensor1 * tensor2
print(mul_tensor)

tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])


In [39]:
div_tensor = tensor1 / tensor2
print(div_tensor)

tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])


In [40]:
torch.add(tensor1, tensor2)

tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])

In [41]:
torch.sub(tensor1, tensor2)

tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])

In [42]:
torch.mul(tensor1, tensor2)

tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])

In [43]:
torch.div(tensor1, tensor2)

tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])

In [44]:
torch.matmul(tensor1, tensor2)

tensor([[[ 31.,  34.],
         [ 71.,  78.]],

        [[155., 166.],
         [211., 226.]]])